### ISSUE TITLE
Need help,the content is only '{}'

### ISSUE THREAD

**Issue by AreChen** [biswajit-saha/ghost-theme-translator#1]
Hey bro,In the free EDGE theme, no fields can be resolved.
[EDGE THEME](https://ghost.org/themes/edge/)
Command line:
`gtt c -n Edge-main`
It created a folder named 'locals' and a file named 'en.json' in the root directory, but the content is only '{}'

**Comment by biswajit-saha** [comment]
Ghost has a translate helper (https://ghost.org/docs/themes/helpers/translate/) The translatable texts in the theme should be wrapped in this helper to be detected by ghost-theme-translator.

Find all the strings and wrap those using that helper in the correct way. After that use the same command.

**Comment by AreChen** [comment]
Thank you, I will give it a try.
